export const datos = [
    {
        id: 1,
        name: "Fernet Branca",
        description: "Fernet Branca 750cc",
        price: 1000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 2,
        name: "Fernet Buhero",
        description: "Descripción del producto 2",
        price: 2000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 3,
        name: "Cerveza Quilmes",
        description: "Descripción del producto 3",
        price: 3000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 4,
        name: "Schneider",
        description: "Descripción del producto 4",
        price: 4000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 5,
        name: "Producto 5",
        description: "Descripción del producto 5",
        price: 5000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 6,
        name: "Producto 6",
        description: "Descripción del producto 6",
        price: 6000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 7,
        name: "Producto 7",
        description: "Descripción del producto 7",
        price: 7000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 8,
        name: "Producto 8",
        description: "Descripción del producto 8",
        price: 8000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 9,
        name: "Producto 9",
        description: "Descripción del producto 9",
        price: 9000,
        image: "https://via.placeholder.com/150",
    },
    {
        id: 10,
        name: "Producto 10",
        description: "Descripción del producto 10",
        price: 10000,
        image: "https://via.placeholder.com/150",
    },
];
